URL: https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/course-zoomcamp/cohorts/2022/01-intro/homework.md

# Question 1

In [2]:
import numpy as np
np.__version__

'1.21.5'

# Question 2

In [8]:
import pandas as pd
df = pd.read_csv('Datasets/car_prediction.csv')

In [9]:
df.count()

Make                 11914
Model                11914
Year                 11914
Engine Fuel Type     11911
Engine HP            11845
Engine Cylinders     11884
Transmission Type    11914
Driven_Wheels        11914
Number of Doors      11908
Market Category       8172
Vehicle Size         11914
Vehicle Style        11914
highway MPG          11914
city mpg             11914
Popularity           11914
MSRP                 11914
dtype: int64

# Question 3

In [13]:
df.Make.value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

# Question 3

In [16]:
df[df.Make == 'Audi'].Model.nunique()

34

# Question 4

In [18]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

# Question 6

In [24]:
df["Engine Cylinders"].median()

6.0

In [30]:
df["Engine Cylinders"].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [33]:
df["Engine Cylinders"]=df["Engine Cylinders"].fillna(4)

In [34]:
df["Engine Cylinders"].median()

6.0

# Question 7

In [36]:
df_lotus = df[df.Make=="Lotus"].loc[:, ["Engine HP", "Engine Cylinders"]]

In [40]:
X = df_lotus.drop_duplicates().to_numpy()

In [41]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [51]:
XTX = np.matmul(X.T, X)

In [52]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [53]:
XTX_inverse = np.linalg.inv(XTX)

In [54]:
XTX_inverse

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [55]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [59]:
w=np.matmul(np.matmul(XTX_inverse, X.T), y)

In [60]:
w

array([  4.59494481, -63.56432501])